### ISSUE TITLE
Is there an asynchronous API to render after some times to wait data of stateful components to load?

### ISSUE THREAD

**Issue by gre** [revivek/oy#57]
I have stateful components that do work before being ready (wait some data to load, rendering into canvas and then in a base64 image, etc..).

I don't want to move my state in top of the tree because it loses the modularity of components. (and it wouldn't be easy in my usecase anyway)

is it possible we can do this with Oy ?

If not, what is the difference between `Oy.renderTemplate` and doing `ReactDOM.render(vdom,container)` and then `container.innerHTML`? (can I do the extra stuff that Oy.renderTemplate is doing but using ReactDOM.render ?)

Thanks

**Comment by revivek** [comment]
Hi @gre, Oy adheres to the same constraints as React server-side rendering. To my knowledge, there is no way to wait for events from individual components to be "ready", and there is no concept of stateful components with React server-side rendering.

To address your use case, I think you'll have to wait for the necessary data to load at the top level, then pass that data in as props to your component tree root.

`ReactDOM.render` wouldn't work on the server, since there's no DOM to attach the rendered raw HTML to. `Oy.renderTemplate` uses `ReactDOMServer.renderToStaticMarkup(...)`, injects that string into a basic HTML4 [email template string](https://github.com/revivek/oy/blob/master/src/utils/HTML4.js#L45), then returns that string, which is a full email template.

Hope that helps!
